version: "3"
services:
  tribuna_bot:
    build: .
    ports:
      - '8005:8000'
    container_name: tribuna_bot_django
    environment:
      - PROD_TRIBUNA_BOT=True
      - TELEGRAM_BOT_SECRET_TRIBUNA=${INPUT_TELEGRAM_BOT_SECRET_TRIBUNA}
      - CLUB_SERVICE_TOKEN_OUTLINE_BOT=${INPUT_CLUB_SERVICE_TOKEN_OUTLINE_BOT}
    volumes:
      - ./volume/media:/app/media
      - ./volume/db:/app/db
